name: Get IP Address

on:
  workflow_dispatch:

jobs:
  get-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Get IP address
        id: get_ip
        run: |
          IP=$(curl -s https://jsonip.com | jq -r '.ip')
          echo "My IP address is: $IP"
          
      - name: Use IP address
        run: echo "Do something with the IP address ${{ steps.get_ip.outputs.IP }}"
